version: '3.4'

services:
  weatherforecastservice:
    image: weather_service
    build:
      context: .
      dockerfile: WeatherForecastService/Dockerfile
    ports: 
       - "5000:80"

  
  tripsuggestservice:
    image: trip_suggest_service
    build:
      context: .
      dockerfile: SEMicroserviceProject/Dockerfile

    ports:
        - "5001:80" 